apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.volume.pv.name }}
  labels:
    name: {{ .Values.postgres.volume.pv.name }}
spec:
  capacity:
    storage: {{ .Values.postgres.volume.pv.storage }}
  volumeMode: {{ .Values.postgres.volume.pv.volumeMode }}
  accessModes:
    - {{ .Values.postgres.volume.pv.accessMode }}
  hostPath:
    path: {{ .Values.postgres.volume.pv.path }}